package com.catoxide.dungeonblockvarient;

import net.minecraft.client.renderer.ItemBlockRenderTypes;
import net.minecraft.client.renderer.RenderType;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;

@Mod(DungeonBlockVarient.MODID)
@Mod.EventBusSubscriber
public class DungeonBlockVarient {
    public static final String MODID = "dungeonblockvarient";

    public DungeonBlockVarient() {
        // 注册方块和物品
        ModBlocks.BLOCKS.register(FMLJavaModLoadingContext.get().getModEventBus());
        ModItems.ITEMS.register(FMLJavaModLoadingContext.get().getModEventBus());


        // 注册其他事件监听器
        MinecraftForge.EVENT_BUS.register(this);

    }

    @Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
    public static class ClientModEvents {
        @SubscribeEvent
        public static void onClientSetup(FMLClientSetupEvent event) {

            event.enqueueWork(() -> {
                System.out.println("Setting up render layers for " + ModBlocks.BLOCKS.getEntries().size() + " blocks");

                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TRIPWIRE.get(), RenderType.tripwire());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GRASS_BLOCK.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_IRON_BARS.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GLASS_PANE.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TRIPWIRE_HOOK.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_HOPPER.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CHAIN.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_JUNGLE_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_OAK_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SPRUCE_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ACACIA_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CHERRY_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BIRCH_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DARK_OAK_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_AZALEA_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FLOWERING_AZALEA_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MANGROVE_ROOTS.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MANGROVE_LEAVES.get(), RenderType.cutoutMipped());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_OAK_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SPRUCE_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BIRCH_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_JUNGLE_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ACACIA_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CHERRY_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DARK_OAK_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GLASS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WHITE_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ORANGE_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MAGENTA_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIGHT_BLUE_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_YELLOW_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIME_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PINK_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GRAY_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIGHT_GRAY_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CYAN_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PURPLE_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BLUE_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BROWN_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GREEN_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_RED_BED.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BLACK_BED.get(), RenderType.cutout());
                // ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POWERED_RAIL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DETECTOR_RAIL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_COBWEB.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GRASS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FERN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_BUSH.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SEAGRASS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TALL_SEAGRASS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DANDELION.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POPPY.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BLUE_ORCHID.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ALLIUM.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_AZURE_BLUET.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_RED_TULIP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ORANGE_TULIP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WHITE_TULIP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PINK_TULIP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_OXEYE_DAISY.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CORNFLOWER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WITHER_ROSE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LILY_OF_THE_VALLEY.get(), RenderType.cutout());
                //  ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BROWN_MUSHROOM.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_RED_MUSHROOM.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TORCH.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WALL_TORCH.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SOUL_TORCH.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SOUL_WALL_TORCH.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FIRE.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SOUL_FIRE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SPAWNER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_REDSTONE_WIRE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WHEAT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_OAK_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LADDER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_RAIL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_IRON_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_REDSTONE_TORCH.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_REDSTONE_WALL_TORCH.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CACTUS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SUGAR_CANE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_REPEATER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_OAK_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SPRUCE_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BIRCH_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_JUNGLE_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ACACIA_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CHERRY_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DARK_OAK_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CRIMSON_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WARPED_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MANGROVE_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BAMBOO_TRAPDOOR.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ATTACHED_PUMPKIN_STEM.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ATTACHED_MELON_STEM.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PUMPKIN_STEM.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MELON_STEM.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_VINE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GLOW_LICHEN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LILY_PAD.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_NETHER_WART.get(), RenderType.cutout());
                //ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BREWING_STAND.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_COCOA.get(), RenderType.cutout());
                //ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BEACON.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FLOWER_POT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_OAK_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_SPRUCE_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_BIRCH_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_JUNGLE_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_ACACIA_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_CHERRY_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_DARK_OAK_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_MANGROVE_PROPAGULE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_FERN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_DANDELION.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_POPPY.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_BLUE_ORCHID.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_ALLIUM.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_AZURE_BLUET.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_RED_TULIP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_ORANGE_TULIP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_WHITE_TULIP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_PINK_TULIP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_OXEYE_DAISY.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_CORNFLOWER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_LILY_OF_THE_VALLEY.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_WITHER_ROSE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_RED_MUSHROOM.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_BROWN_MUSHROOM.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_DEAD_BUSH.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_CACTUS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_AZALEA.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_FLOWERING_AZALEA.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_TORCHFLOWER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CARROTS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTATOES.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_COMPARATOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ACTIVATOR_RAIL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_IRON_TRAPDOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SUNFLOWER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LILAC.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ROSE_BUSH.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PEONY.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TALL_GRASS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LARGE_FERN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SPRUCE_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BIRCH_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_JUNGLE_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ACACIA_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CHERRY_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DARK_OAK_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MANGROVE_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BAMBOO_DOOR.get(), RenderType.cutout());
                //ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_END_ROD.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CHORUS_PLANT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CHORUS_FLOWER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TORCHFLOWER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TORCHFLOWER_CROP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PITCHER_PLANT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PITCHER_CROP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BEETROOTS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_KELP.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_KELP_PLANT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TURTLE_EGG.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_TUBE_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_BRAIN_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_BUBBLE_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_FIRE_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_HORN_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TUBE_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BRAIN_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BUBBLE_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FIRE_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_HORN_CORAL.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_TUBE_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_BRAIN_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_BUBBLE_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_FIRE_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_HORN_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TUBE_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BRAIN_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BUBBLE_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FIRE_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_HORN_CORAL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_TUBE_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_BRAIN_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_BUBBLE_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_FIRE_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_DEAD_HORN_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TUBE_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BRAIN_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BUBBLE_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FIRE_CORAL_WALL_FAN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_HORN_CORAL_WALL_FAN.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SEA_PICKLE.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CONDUIT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BAMBOO_SAPLING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BAMBOO.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_BAMBOO.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SCAFFOLDING.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_STONECUTTER.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LANTERN.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SOUL_LANTERN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CAMPFIRE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SOUL_CAMPFIRE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SWEET_BERRY_BUSH.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WEEPING_VINES.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WEEPING_VINES_PLANT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TWISTING_VINES.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TWISTING_VINES_PLANT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_NETHER_SPROUTS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CRIMSON_FUNGUS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WARPED_FUNGUS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CRIMSON_ROOTS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WARPED_ROOTS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_CRIMSON_FUNGUS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_WARPED_FUNGUS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_CRIMSON_ROOTS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POTTED_WARPED_ROOTS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CRIMSON_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WARPED_DOOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_POINTED_DRIPSTONE.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SMALL_AMETHYST_BUD.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MEDIUM_AMETHYST_BUD.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LARGE_AMETHYST_BUD.get(), RenderType.cutout());
//            ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_AMETHYST_CLUSTER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIGHTNING_ROD.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CAVE_VINES.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CAVE_VINES_PLANT.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SPORE_BLOSSOM.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FLOWERING_AZALEA.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_AZALEA.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MOSS_CARPET.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PINK_PETALS.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BIG_DRIPLEAF.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BIG_DRIPLEAF_STEM.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SMALL_DRIPLEAF.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_HANGING_ROOTS.get(), RenderType.cutout());
                //ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SCULK_SENSOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CALIBRATED_SCULK_SENSOR.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SCULK_VEIN.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SCULK_SHRIEKER.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MANGROVE_PROPAGULE.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MANGROVE_LOG.get(), RenderType.cutout());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FROGSPAWN.get(), RenderType.cutout());
                //ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ICE.get(), RenderType.translucent());
                //ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_NETHER_PORTAL.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WHITE_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ORANGE_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MAGENTA_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIGHT_BLUE_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_YELLOW_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIME_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PINK_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GRAY_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIGHT_GRAY_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CYAN_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PURPLE_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BLUE_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BROWN_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GREEN_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_RED_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BLACK_STAINED_GLASS.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_WHITE_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_ORANGE_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_MAGENTA_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIGHT_BLUE_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_YELLOW_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIME_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PINK_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GRAY_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_LIGHT_GRAY_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_CYAN_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_PURPLE_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BLUE_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BROWN_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_GREEN_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_RED_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BLACK_STAINED_GLASS_PANE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_SLIME_BLOCK.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_HONEY_BLOCK.get(), RenderType.translucent());
                //ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_FROSTED_ICE.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_BUBBLE_COLUMN.get(), RenderType.translucent());
                ItemBlockRenderTypes.setRenderLayer(ModBlocks.ANCIENT_TINTED_GLASS.get(), RenderType.translucent());

            });
        }
    }
}